export type SimulationPhase =
  | "IDLE"
  | "RUNNING"
  | "PAUSED"
  | "STOPPED"
  | "COMPLETED";

export type TelemetryType = "DOM" | "NETWORK" | "CONSOLE" | "CRASH";

export interface SimulationStep {
  phase: string;
  action: string;
  status: string;
  type: TelemetryType;
  error?: boolean;
}

export const SIMULATION_STEPS: SimulationStep[] = [
  {
    phase: "Form Flooding",
    action:
      "Inputting 5000-character payload into 'username' field",
    status: "Testing Validation",
    type: "DOM",
  },
  {
    phase: "Form Flooding",
    action:
      "Spamming 'Submit Button' [DOM Selector: #auth-submit] 12x rapidly",
    status: "CONGESTION WARNING",
    type: "DOM",
  },
  {
    phase: "API Flooding",
    action: "POST /api/v1/auth/register -> Payload: Empty String",
    status: "HTTP 500 INTERNAL SERVER ERROR",
    type: "NETWORK",
    error: true,
  },
  {
    phase: "API Flooding",
    action:
      "Intercepted Stack Trace: Uncaught TypeError: Cannot read properties of undefined (reading 'token')",
    status: "EXCEPTION THROWN",
    type: "CONSOLE",
    error: true,
  },
  {
    phase: "Race Conditions",
    action:
      "Triggering rapid back-and-forth route transitions between Dashboard and Settings",
    status: "Testing State Resilience",
    type: "DOM",
  },
  {
    phase: "Memory Stress",
    action:
      "Simulating UI Freeze via infinite layout repaint loop detection",
    status: "UNRESPONSIVE WINDOW DETECTED",
    type: "CRASH",
    error: true,
  },
];

export function formatTelemetryLine(step: SimulationStep, ts: string): string {
  const err = step.error ? " ERR" : "";
  return `[${ts}] <${step.type}${err}> ${step.phase} — ${step.action} :: ${step.status}`;
}

export function buildBugReportMarkdown(opts: {
  targetUrl: string;
  outcome: "COMPLETED" | "STOPPED";
  stepsExecuted: SimulationStep[];
}): string {
  const { targetUrl, outcome, stepsExecuted } = opts;
  const errors = stepsExecuted.filter((s) => s.error);
  const header =
    outcome === "COMPLETED"
      ? "Run finished — full stress matrix executed."
      : "Run terminated by operator — partial trace retained.";

  return `# UserSim — Autonomous Stress Test Report

**Target:** \`${targetUrl}\`  
**Outcome:** ${outcome}  
**Observed steps:** ${stepsExecuted.length} / ${SIMULATION_STEPS.length}

---

## Executive summary

${header}

UserSim replayed high-entropy interaction paths against the target surface, combining **DOM saturation**, **API disorder**, and **navigation churn** to surface brittle validation, race-prone handlers, and unguarded promise chains.

---

## Severity matrix

| Phase | Type | Status | Error |
|-------|------|--------|-------|
${stepsExecuted
  .map(
    (s) =>
      `| ${s.phase} | ${s.type} | ${s.status} | ${s.error ? "yes" : "no"} |`
  )
  .join("\n")}

---

## Flagged incidents

${
  errors.length
    ? errors
        .map(
          (e) =>
            `### ${e.phase} (${e.type})\n\n- **Signal:** ${e.status}\n- **Trace:** \`${e.action.replace(/`/g, "'")}\`\n`
        )
        .join("\n")
    : "_No error-class signals in the captured window._\n"
}

---

## Recommended next actions

1. Harden **auth/register** against empty payloads and normalize error envelopes before token access.
2. Debounce **#auth-submit** and enforce **client + server** validation on oversized username fields.
3. Add **route transition** cancellation tokens so dashboard/settings swaps cannot interleave stale responses.
4. Profile **layout / paint** under rapid subtree toggles; cap virtualized lists and memoize hot paths.

---

*Generated by UserSim — synthetic operator, real telemetry shape.*
`;
}
